<?php

// Problem
foreach ($all as $a) {
    if ($a > 2) {
        // sample code ...
        // sample code ...
        // sample code ...
        // sample code ...
    }
}


// Solution
foreach ($all as $a) {
    if ($a <= 2) {
        continue;
    }

    // sample code ...
    // sample code ...
    // sample code ...
    // sample code ...
}
